// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ZeloApi.Net.Data;

#nullable disable

namespace ZeloApi.Net.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909144814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZeloApi.Net.Models.Pet", b =>
                {
                    b.Property<long>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PET_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PetId"));

                    b.Property<string>("Castrado")
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("CASTRADO");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("ESPECIE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("NUMBER(6,2)")
                        .HasColumnName("PESO_KG");

                    b.Property<string>("Raca")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("RACA");

                    b.Property<string>("Sexo")
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("SEXO");

                    b.HasKey("PetId");

                    b.ToTable("ZELO_PET");
                });

            modelBuilder.Entity("ZeloApi.Net.Models.PetTutor", b =>
                {
                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PET_ID");

                    b.Property<long>("TutorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<DateTime>("DataVinculo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_VINCULO");

                    b.Property<string>("ResponsavelPrincipal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("RESPONSAVEL_PRINCIPAL");

                    b.HasKey("PetId", "TutorId");

                    b.HasIndex("TutorId");

                    b.ToTable("ZELO_PET_TUTOR");
                });

            modelBuilder.Entity("ZeloApi.Net.Models.Tutor", b =>
                {
                    b.Property<long>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TUTOR_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TutorId"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("CIDADE");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Telefone")
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)")
                        .HasColumnName("TELEFONE");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("TutorId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("ZELO_TUTOR");
                });

            modelBuilder.Entity("ZeloApi.Net.Models.Usuario", b =>
                {
                    b.Property<long>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USUARIO_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UsuarioId"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("NVARCHAR2(160)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NOME");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA_HASH");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_USUARIO");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ZELO_USUARIO");
                });

            modelBuilder.Entity("ZeloApi.Net.Models.PetTutor", b =>
                {
                    b.HasOne("ZeloApi.Net.Models.Pet", "Pet")
                        .WithMany("PetTutores")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZeloApi.Net.Models.Tutor", "Tutor")
                        .WithMany("PetTutores")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("ZeloApi.Net.Models.Tutor", b =>
                {
                    b.HasOne("ZeloApi.Net.Models.Usuario", "Usuario")
                        .WithOne("Tutor")
                        .HasForeignKey("ZeloApi.Net.Models.Tutor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZeloApi.Net.Models.Pet", b =>
                {
                    b.Navigation("PetTutores");
                });

            modelBuilder.Entity("ZeloApi.Net.Models.Tutor", b =>
                {
                    b.Navigation("PetTutores");
                });

            modelBuilder.Entity("ZeloApi.Net.Models.Usuario", b =>
                {
                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
