import { useRouter } from "expo-router";
import React from "react";
import { Alert, FlatList, RefreshControl, StyleSheet, Text, View } from "react-native";

import { Card, EmptyState, ErrorState, LoadingState, PrimaryButton, SectionTitle, StatusBadge } from "@/components/zelo-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAlertas, useCancelAlerta, useConfirmAlerta, useDeleteAlerta } from "@/hooks/use-zelo";
import { useColors } from "@/hooks/use-colors";
import type { CareAlert } from "@/types/api";
import { useAuth } from "@/lib/auth-context";

export default function AlertsScreen() { const colors = useColors(); const router = useRouter(); const { user } = useAuth(); const alerts = useAlertas(); const confirm = useConfirmAlerta(); const cancel = useCancelAlerta(); const remove = useDeleteAlerta(); const professional = user?.tipo === "VETERINARIO" || user?.tipo === "GESTOR"; if (alerts.isLoading) return <ScreenContainer className="p-5"><LoadingState label="Carregando alertas..." /></ScreenContainer>; if (alerts.error && !alerts.data) return <ScreenContainer className="p-5"><ErrorState message={alerts.error instanceof Error ? alerts.error.message : "Verifique a conexão com a API Java."} onRetry={() => void alerts.refetch()} /></ScreenContainer>; const items = alerts.data ?? []; function actions(item: CareAlert) { const options: Parameters<typeof Alert.alert>[2] = [{ text: "Fechar" }]; if (item.status === "PENDENTE" || item.status === "ENVIADO") options.push({ text: "Marcar como concluído", onPress: () => confirm.mutate(item.id) }); if (item.status !== "CONCLUIDO" && item.status !== "CANCELADO") options.push({ text: "Cancelar alerta", style: "destructive", onPress: () => cancel.mutate(item.id) }); options.push({ text: "Excluir", style: "destructive", onPress: () => remove.mutate(item.id) }); Alert.alert(item.titulo, item.petNome ?? "Alerta", options); } return <ScreenContainer className="p-5"><FlatList data={items} keyExtractor={(item) => String(item.id)} refreshControl={<RefreshControl refreshing={alerts.isFetching} onRefresh={() => void alerts.refetch()} tintColor={colors.primary} />} contentContainerStyle={items.length ? styles.list : styles.emptyList} ListHeaderComponent={<View style={styles.header}><SectionTitle title={professional ? "Alertas" : "Plano de cuidado"} subtitle={professional ? "Acompanhe os cuidados ativos dos pets." : "Lembretes e acompanhamentos dos seus pets"} />{!professional && <PrimaryButton label="+ Novo alerta" onPress={() => router.push("/(app)/alerta-new" as never)} />}</View>} ListEmptyComponent={<EmptyState title="Tudo em dia" description="Nenhum alerta de cuidado foi encontrado." />} renderItem={({ item }) => <AlertCard item={item} colors={colors} onActions={() => actions(item)} />} /></ScreenContainer>; }
function AlertCard({ item, colors, onActions }: { item: CareAlert; colors: ReturnType<typeof useColors>; onActions: () => void }) { const tone = item.status === "CONCLUIDO" ? "success" : item.status === "CANCELADO" ? "danger" : item.status === "ENVIADO" ? "info" : "warning"; return <Card style={styles.card}><View style={styles.top}><View style={[styles.icon, { backgroundColor: `${colors.warning}18` }]}><Text style={{ fontSize: 22 }}>{item.tipo === "VACINA" ? "💉" : item.tipo === "CHECKUP" ? "🩺" : "⏰"}</Text></View><View style={styles.copy}><Text style={[styles.title, { color: colors.foreground }]}>{item.titulo}</Text><Text style={[styles.meta, { color: colors.muted }]}>{item.petNome ?? "Pet"} · previsto para {item.dataPrevista}</Text></View><StatusBadge label={item.status} tone={tone} /></View>{item.descricao ? <Text style={[styles.description, { color: colors.muted }]}>{item.descricao}</Text> : null}<Text style={[styles.manage, { color: colors.primary }]} onPress={onActions}>Gerenciar alerta</Text></Card>; }
const styles = StyleSheet.create({ list: { gap: 14, paddingBottom: 28 }, emptyList: { flexGrow: 1 }, header: { gap: 6, marginBottom: 8 }, card: { gap: 13 }, top: { flexDirection: "row", alignItems: "flex-start", gap: 11 }, icon: { width: 46, height: 46, borderRadius: 15, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, gap: 4 }, title: { fontSize: 16, fontWeight: "800" }, meta: { fontSize: 12, lineHeight: 17 }, description: { fontSize: 13, lineHeight: 19 }, manage: { borderTopWidth: 1, borderTopColor: "#E5E7EB", paddingTop: 12, fontSize: 13, fontWeight: "800" }, });
