import { useRouter } from "expo-router";
import React, { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";

import { BrandMark, Card, PrimaryButton, SectionTitle } from "@/components/zelo-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useAuth } from "@/lib/auth-context";

const roleLabel = { TUTOR: "Tutor", VETERINARIO: "Veterinário", GESTOR: "Gestor" } as const;
export default function ProfileScreen() { const colors = useColors(); const router = useRouter(); const { user, logout } = useAuth(); const [loading, setLoading] = useState(false); async function exit() { setLoading(true); await logout(); setLoading(false); router.replace("/(auth)/login"); } return <ScreenContainer className="p-5"><ScrollView contentContainerStyle={styles.content}><BrandMark /><View style={styles.profileHero}><View style={[styles.avatar, { backgroundColor: colors.primary }]}><Text style={styles.avatarText}>{user?.nome?.charAt(0).toUpperCase() ?? "Z"}</Text></View><Text style={[styles.name, { color: colors.foreground }]}>{user?.nome ?? "Usuário"}</Text><Text style={[styles.email, { color: colors.muted }]}>{user?.email}</Text><Text style={[styles.role, { color: colors.primary }]}>{user?.tipo ? roleLabel[user.tipo] : "Usuário"}</Text></View><Card><SectionTitle title="Dados da conta" subtitle="Informações vindas da API Java" /><Info label="Nome" value={user?.nome} colors={colors} /><Info label="E-mail" value={user?.email} colors={colors} /><Info label="Perfil de acesso" value={user?.tipo ? roleLabel[user.tipo] : undefined} colors={colors} /><Info label="Cidade" value={user?.cidade ?? "Não informado"} colors={colors} /></Card><Card style={styles.accessCard}><Text style={[styles.accessTitle, { color: colors.foreground }]}>Seu acesso</Text><Text style={[styles.accessText, { color: colors.muted }]}>{user?.tipo === "TUTOR" ? "Você pode cadastrar pets, abrir triagens e acompanhar o plano de cuidado." : "Você pode acompanhar as filas e os cuidados da clínica conforme as permissões do seu perfil."}</Text></Card><PrimaryButton label="Sair da conta" variant="danger" loading={loading} onPress={() => Alert.alert("Sair do Zelo", "Deseja encerrar sua sessão?", [{ text: "Cancelar", style: "cancel" }, { text: "Sair", style: "destructive", onPress: exit }])} /></ScrollView></ScreenContainer>; }
function Info({ label, value, colors }: { label: string; value?: string | null; colors: ReturnType<typeof useColors> }) { return <View style={[styles.info, { borderTopColor: colors.border }]}><Text style={[styles.infoLabel, { color: colors.muted }]}>{label}</Text><Text style={[styles.infoValue, { color: colors.foreground }]}>{value || "Não informado"}</Text></View>; }
const styles = StyleSheet.create({ content: { gap: 18, paddingBottom: 32 }, profileHero: { alignItems: "center", gap: 5, paddingVertical: 8 }, avatar: { width: 82, height: 82, borderRadius: 30, alignItems: "center", justifyContent: "center", marginBottom: 7 }, avatarText: { color: "#FFF", fontSize: 34, fontWeight: "800" }, name: { fontSize: 25, fontWeight: "800" }, email: { fontSize: 14 }, role: { fontSize: 13, fontWeight: "800", marginTop: 3 }, info: { borderTopWidth: 1, paddingVertical: 12, gap: 3 }, infoLabel: { fontSize: 12 }, infoValue: { fontSize: 15, fontWeight: "700" }, accessCard: { gap: 7 }, accessTitle: { fontSize: 17, fontWeight: "800" }, accessText: { fontSize: 14, lineHeight: 21 }, });
